import argparse
from test_generator import TestsGenerator

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        'Create a test set from a given dataset. '
        'Test forms are generated by creating hard links to existing dataset form files')
    parser.add_argument('--forms', required=True,
                        help='The path of the directory containing the dataset forms.')
    parser.add_argument('--size', type=int, required=True,
                        help='The number of test cases to generate.')
    parser.add_argument('--metadata', default='dataset_forms_metadata.txt',
                        help='The path of the dataset forms metadata file.')

    args = parser.parse_args()
    TestsGenerator(args.metadata, args.forms).generate_test_set(args.size)
